# Generated by Django 3.2.13 on 2022-05-15 11:14

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
